// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuM71ELkvgDD5FaoS2o6OC-prkYBO-YaA',
    appId: '1:454951257673:web:b66fd72c31bbfe95576198',
    messagingSenderId: '454951257673',
    projectId: 'expense-tracker-f7066',
    authDomain: 'expense-tracker-f7066.firebaseapp.com',
    storageBucket: 'expense-tracker-f7066.firebasestorage.app',
    measurementId: 'G-B9LYN3CZP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OJO1CK8l70Ky0zLYAQiKOMZi4_KdLOA',
    appId: '1:454951257673:android:aac0aa1b1aa1c850576198',
    messagingSenderId: '454951257673',
    projectId: 'expense-tracker-f7066',
    storageBucket: 'expense-tracker-f7066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jUFV2K9Qr_mqC7oacUgI2xYVt6IAsWA',
    appId: '1:454951257673:ios:4c531f0b062ef9bd576198',
    messagingSenderId: '454951257673',
    projectId: 'expense-tracker-f7066',
    storageBucket: 'expense-tracker-f7066.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jUFV2K9Qr_mqC7oacUgI2xYVt6IAsWA',
    appId: '1:454951257673:ios:4c531f0b062ef9bd576198',
    messagingSenderId: '454951257673',
    projectId: 'expense-tracker-f7066',
    storageBucket: 'expense-tracker-f7066.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuM71ELkvgDD5FaoS2o6OC-prkYBO-YaA',
    appId: '1:454951257673:web:c024f71a1b3409eb576198',
    messagingSenderId: '454951257673',
    projectId: 'expense-tracker-f7066',
    authDomain: 'expense-tracker-f7066.firebaseapp.com',
    storageBucket: 'expense-tracker-f7066.firebasestorage.app',
    measurementId: 'G-K2B7H1BBXD',
  );
}
